name: Build and push Docker image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build image
        run: |
          IMAGE=${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPO }}:${IMAGE_TAG}
          IMAGE_STAGE=${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPO }}:stage
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "IMAGE_STAGE=$IMAGE_STAGE" >> $GITHUB_ENV
          docker build . -t $IMAGE -t ${IMAGE_STAGE} --target prod-distroless
      - name: Push image
        run: |
          docker push $IMAGE
          docker push $IMAGE_STAGE
      - name: Get digest
        run: |
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE | cut -d'@' -f2)
          echo "DIGEST=$DIGEST" >> $GITHUB_ENV
      - name: Create release manifest
        run: |
          cat <<EOF > release-manifest.json
          {
           "commit": "${IMAGE_TAG}",
           "promotedAt": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "promotedBy": "${{ github.actor }}",
            "services": {
             "orders_service": {
                "image": "${IMAGE}",
                "digest": "${DIGEST}"
              }
            }
          } 
          EOF

      - uses: actions/upload-artifact@v4
        with:
          name: release-manifest
          path: release-manifest.json

      - name: Force ECS Service Restart
        run: |
          aws ecs update-service \
          --cluster ${{ vars.ECS_CLUSTER }} \
          --service ${{ vars.ECS_SERVICE }} \
          --force-new-deployment

      - name: Health check
        run: |
          sleep 30  # wait for ECS to spin up new task
          curl --fail --retry 5 --retry-delay 10 \
            ${{ vars.API_URL }}/health