name: Build and push Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build image
        run: |
          IMAGE=741773097593.dkr.ecr.eu-north-1.amazonaws.com/nest-app:${IMAGE_TAG}
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build . -t $IMAGE --target prod-distroless
      - name: Push image
        run: |
          docker push $IMAGE
      - name: Get digest
        run: |
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE | cut -d'@' -f2)
          echo "DIGEST=$DIGEST" >> $GITHUB_ENV
      - name: Create release manifest
        run: |
          cat <<EOF > release-manifest.json
          {
           "commit": "${IMAGE_TAG}",
           "createdAt": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "services": {
             "orders_service": {
                "image": "${IMAGE}",
                "digest": "${DIGEST}"
              }
            }
          } 
          EOF

      - uses: actions/upload-artifact@v4
        with:
          name: release-manifest
          path: release-manifest.json

  

